### ISSUE TITLE
New blink menu for quick actions

### ISSUE THREAD

**Issue by yury** [blinksh/blink#1800]
Current problems:
- 3f tab is not discoverable and doesn't work in vscode
- limited layout (we need more staff to fit there, like geo lock, snips and config)

Proposed solution - New reworked menu bar.

![](https://cdn.discordapp.com/attachments/442023972138123276/1123961420434903193/image.png)

We build new bar based on UIButtons and UIMenus.

- new 3 dots (more actions) menu at the right.
- left icon + text on large screens
- icons only on tine screens
- some actions always in 3 dots menu. Like `config`, `hosts`
- kb shortcut for bar is double cmd.

```[tasklist]
### Tasks
- [x] Implement functionality
- [x] Visual improvements
- [x] Enable ' Disable geo from bar
- [ ] We need a visual trigger for the bar -> Push
```

**Comment by carloscabanero** [comment]
Functionality 
- [x] Layout buttons still not working.
- [x] Hide Geo track for now.

UX improvements
- [x] Improve dismiss when tapping outside.
- [x] Software keyboard is causing issues with the bar and animations.
- [x] Compact mode is not remembered when showing.

Visual improvements
- [ ] Animations are different when the bar goes on / off. -> Push
- [ ] Organize actions. -> Push
- [ ] Improve light mode. -> Push
