### ISSUE TITLE
Update fonts repository to use Mono Nerd fonts

### ISSUE THREAD

**Issue by carloscabanero** [blinksh/blink#1874]
We have requests like https://github.com/blinksh/blink/discussions/1873?converting=1, https://discord.com/channels/441939332442619905/441940293240225793/1153467137915093142, very often.

This is usually fixed by using the Mono version of the font, not the "Regular" or "Proportional". But our repository has not been updating the fonts for a while and we are not doing this properly anymore.

Users expect a plug-and-play experience with the fonts. We should clean all fonts there and offer proper patched CSS fonts, ready to use.

If someone wants to take on a small project like this, please let me know. It would be great to give a bump to our repository. We can do it easily with a Python script.
```[tasklist]
### Tasks
- [ ] New json files
- [ ] Font generation with GH token
- [ ] Test resulting fonts
```
